import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { loadConfig } from '../config.js';
import { logger } from '../shared/logger.js';

function latestReport(baseDir, moduleName) {
    const directory = join(baseDir, moduleName);
    if (!existsSync(directory)) return null;
    const files = readdirSync(directory)
        .filter(file => file.startsWith(`${moduleName}_`) && file.endsWith('.json'))
        .sort()
        .reverse();
    return files.length
        ? JSON.parse(readFileSync(join(directory, files[0]), 'utf8'))
        : null;
}

export async function runReport(options = {}) {
    const config = loadConfig(options);
    const format = options.format || 'markdown';
    if (!['markdown', 'json'].includes(format)) {
        throw new Error(`Unsupported report format: ${format}`);
    }

    mkdirSync(config.reportsDir, { recursive: true });
    const report = {
        analysis: latestReport(config.reportsDir, 'analysis'),
        migration: latestReport(config.logsDir, 'migration'),
        validation: latestReport(config.reportsDir, 'validation'),
        typeReview: latestReport(config.reportsDir, 'type-review'),
    };

    if (format === 'json') {
        const outputPath = join(config.reportsDir, 'migration-report.json');
        writeFileSync(outputPath, `${JSON.stringify(report, null, 2)}\n`);
        logger.success(`JSON report saved: ${outputPath}`);
        return outputPath;
    }

    const outputPath = join(config.reportsDir, 'MIGRATION_REPORT.md');
    writeFileSync(outputPath, generateMarkdownReport(report));
    logger.success(`Markdown report saved: ${outputPath}`);
    return outputPath;
}

export function generateMarkdownReport({ analysis, migration, validation, typeReview }) {
    const lines = [
        '# JavaScript to TypeScript Migration Report',
        '',
        `Generated: ${new Date().toISOString()}`,
        '',
    ];

    if (analysis?.summary) {
        const summary = analysis.summary;
        lines.push('## Analysis', '');
        lines.push('| Metric | Value |', '| --- | ---: |');
        lines.push(`| Source files | ${summary.totalFiles} |`);
        lines.push(`| TypeScript targets | ${summary.tsTargets} |`);
        lines.push(`| TSX targets | ${summary.tsxTargets} |`);
        lines.push(`| High complexity | ${summary.highComplexity} |`, '');
    }

    if (migration?.stats) {
        const stats = migration.stats;
        lines.push('## Migration', '');
        lines.push('| Metric | Value |', '| --- | ---: |');
        lines.push(`| Processed | ${stats.total} |`);
        lines.push(`| Successful | ${stats.success} |`);
        lines.push(`| Failed | ${stats.failed} |`);
        lines.push(`| Manual review | ${stats.manualReview || 0} |`);
        lines.push(`| AI tokens reported | ${stats.aiTokens || 0} |`, '');
    }

    if (validation) {
        lines.push('## Validation', '');
        lines.push(`Status: ${validation.passed ? 'Passed' : 'Failed'}`, '');
        lines.push(`Files checked: ${validation.totalFiles}`);
        lines.push(`TypeScript errors: ${validation.errorCount}`, '');
    }

    if (typeReview) {
        lines.push('## Review markers', '');
        lines.push(`Explicit any: ${typeReview.anyCount}`);
        lines.push(`@ts-expect-error: ${typeReview.tsExpectErrorCount}`);
        lines.push(`@ts-ignore: ${typeReview.tsIgnoreCount}`, '');
    }

    lines.push('## Next steps', '');
    lines.push('1. Review all generated changes as application code.');
    lines.push('2. Resolve compiler errors and flagged type-review markers.');
    lines.push('3. Run the application test suite against the migrated output.');
    lines.push('4. Merge the migration in small, reviewable batches.', '');
    lines.push('Generated by Refactra JavaScript to TypeScript.');
    return `${lines.join('\n')}\n`;
}
